### ISSUE TITLE
Number of savestates shown on the kz menu

### ISSUE THREAD

**Issue by MikamiHero** [krimtonz/kz#9]
Hey devs,

I noticed when making savestates and exporting them to my SD card, then even though I have more than 7 states saved into a directory, it only shows the first 7 when bringing up the `kz` menu and going into `states` to either import or export. I've confirmed the states are there by checking the SD card contents on my computer.

Is this an already known UI issue?

**Comment by MikamiHero** [comment]
I'm not sure what's happened, but I believe it may have resolved itself. It was persisting for a few days, but not sure what changed. Closing issue.

**Comment by krimtonz** [comment]
That is very interesting. I will take a look as there is probably something funky in the file system driver.
